#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export TERM="xterm-256color"
export PATH=$PATH:/home/aviral/.cabal/bin/:$HOME/.cargo/bin/

# prompt configuration
export SPACESHIP_NODE_SHOW=false
export SPACESHIP_DIR_TRUNC_REPO=false
export SPACESHIP_JOBS_SHOW=true
export SPACESHIP_EXIT_CODE_SHOW=true

# OPAM configuration
. /home/aviral/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
